### ISSUE TITLE
Limit not honored by Query object

### ISSUE THREAD

**Issue by Gaiidenn** [yiisoft/yii2-sphinx#64]
### What steps will reproduce the problem?
Do a query wich returns more than 1000 rows.

### What's expected?
The exact number of matched rows as result.

### What do you get instead?
Only the first 1000 rows

### Additional info
The ActiveDataProvider object already by-pass this problem. I solved this by myself by adding this line : 
`$query->options['max_matches'] = $offset + $limit;` 
This should also be present directly in the Query object to solve the problem.

| Q                     | A
| --------------------- | ---
| Yii version           | 2.0.6
| Yii Sphinx version    | 2.0.5
| Sphinx server version | 2.2.9-id64-release
| PHP version           | 7.0.9
| Operating system      | Debian 3.16.7

**Comment by klimov-paul** [comment]
This is expected behavior.

> This should also be present directly in the Query object to solve the problem.

No it should not.

**Comment by Gaiidenn** [comment]
This isn't documented

**Comment by klimov-paul** [comment]
???

http://sphinxsearch.com/docs/current.html#sphinxql-select

> 'max_matches' - integer (per-query max matches value)
Maximum amount of matches that the daemon keeps in RAM for each index and can return to the client. Default is 1000.
Introduced in order to control and limit RAM usage, max_matches setting defines how much matches will be kept in RAM while searching each index. Every match found will still be processed; but only best N of them will be kept in memory and return to the client in the end. Assume that the index contains 2,000,000 matches for the query. You rarely (if ever) need to retrieve all of them. Rather, you need to scan all of them, but only choose "best" at most, say, 500 by some criteria (ie. sorted by relevance, or price, or anything else), and display those 500 matches to the end user in pages of 20 to 100 matches. And tracking only the best 500 matches is much more RAM and CPU efficient than keeping all 2,000,000 matches, sorting them, and then discarding everything but the first 20 needed to display the search results page. max_matches controls N in that "best N" amount.
This parameter noticeably affects per-query RAM and CPU usage. Values of 1,000 to 10,000 are generally fine, but higher limits must be used with care. Recklessly raising max_matches to 1,000,000 means that searchd will have to allocate and initialize 1-million-entry matches buffer for every query. That will obviously increase per-query RAM usage, and in some cases can also noticeably impact performance.

**Comment by Gaiidenn** [comment]
OK thank for this fast (but cold) answer !

**Comment by klimov-paul** [comment]
You may use `yii\sphinx\ActiveDataProvider` in case you have a problem with `max_matches`.
See:
https://github.com/yiisoft/yii2-sphinx/blob/master/ActiveDataProvider.php#L55
